version: "3.9"
services:
    db:
        image: mysql
        container_name: db
        ports:
            - "3306:3036"
        environment:
            MYSQL_ROOT_PASSWORD: mesha
            MYSQL_DATABASE: mesha
            MYSQL_USER: mesha
            MYSQL_PASSWORD: mesha
        volumes:
            - ./mysql:/mysql

    minio:
        image: minio/minio
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        volumes:
            - "./minio/datalake:/data" 
        command: server --console-address ":9001" /datalake