version: "3.9"
services:
    db:
        image: mysql
        container_name: db
        ports:
            - "3306:3036"
        environment:
            MYSQL_ROOT_PASSWORD: mesha
            MYSQL_DATABASE: mesha
            MYSQL_USER: mesha
            MYSQL_PASSWORD: mesha
        volumes:
            - ./mysql:/mysql